[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['npm install && cd task-manager-next && npm install']

[phases.build]
cmds = ['cd task-manager-next && npm run build']

[start]
cmd = 'node server.js'
