[phases.setup]
nixPkgs = ['nodejs_22']

[phases.install]
cmds = ['cd task-manager-next && npm install']

[phases.build]
cmds = ['cd task-manager-next && npm run build']

[start]
cmd = 'cd task-manager-next && node server.js'
